Repository Kerdy-iOS/Kerdy-iOS, pull requests merged in 2023-11, with the labels that each got.

#31 [Design] 28 Filter 적용화면 구현
  Core/Sources/Core/Views/ProtrudingBtn.swift
  Kerdy/Kerdy.xcodeproj/project.pbxproj
  Kerdy/Kerdy.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Kerdy/Kerdy.xcodeproj/project.xcworkspace/xcuserdata/idonghyeon.xcuserdatad/UserInterfaceState.xcuserstate
  Kerdy/Kerdy/Common/PrortudingBtn.swift
  Kerdy/Kerdy/Event/View/EventVC.swift
  Kerdy/Kerdy/Filter/DateFilter/Views/DateFilterViewController.swift
  Kerdy/Kerdy/Filter/DateFilter/Views/PeriodView.swift
  Kerdy/Kerdy/Filter/Filter/Models/Tag.swift
  Kerdy/Kerdy/Filter/Filter/Views/DateFilterView.swift
  Kerdy/Kerdy/Filter/Filter/Views/DateSelectBtn.swift
  Kerdy/Kerdy/Filter/Filter/Views/FilterBtn.swift
  Kerdy/Kerdy/Filter/Filter/Views/FilterVC.swift
  Kerdy/Kerdy/Filter/Filter/Views/ProgressFilterView.swift
  Kerdy/Kerdy/Filter/Filter/Views/ResetBtn.swift
  Kerdy/Kerdy/Filter/Filter/Views/TagFilterView.swift
  Kerdy/Kerdy/Filter/Filter/Views/TechTagView.swift
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_calendar_off.imageset/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_calendar_off.imageset/ic_calendar_off.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_calendar_off.imageset/ic_calendar_off@2x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_calendar_off.imageset/ic_calendar_off@3x.png
  Kerdy/Kerdy/TabBar/TabBarVC.swift
Labels: design

#33 [Design] 32 행사 tableView cell UI 최신화
  Kerdy/Kerdy.xcodeproj/project.xcworkspace/xcuserdata/idonghyeon.xcuserdatad/UserInterfaceState.xcuserstate
  Kerdy/Kerdy/Event/View/EventCollectionViewCell.swift
  Kerdy/Kerdy/Event/View/EventTableViewCell.swift
Labels: design

#35 [Fix] 34 컨벤션 수정
  Core/Sources/Core/Views/CategoryBtn.swift
  Core/Sources/Core/Views/CategoryStackView.swift
  Kerdy/Kerdy/InitialSetting/VC/SecondInitialSettingVC.swift
Labels: fix

#41 Feat/#29 initial setting UI
  Core/Sources/Core/Views/CategoryBtn.swift
  Core/Sources/Core/Views/CategoryStackView.swift
  Kerdy/Kerdy/InitialSetting/VC/FourthInitialSettingVC.swift
  Kerdy/Kerdy/InitialSetting/VC/SecondInitialSettingVC.swift
  Kerdy/Kerdy/InitialSetting/VC/ThirdInitialSettingVC.swift
Labels: fix

#39 [Design] 37 작성한 글, 작성한 댓글 UI 구현
  Kerdy/.swiftlint.yml
  Kerdy/Kerdy.xcodeproj/project.pbxproj
  Kerdy/Kerdy/Application/AppDelegate.swift
  Kerdy/Kerdy/Application/SceneDelegate.swift
  Kerdy/Kerdy/Common/NavigationBarView.swift
  Kerdy/Kerdy/Global/Literals/ExternalURL.swift
  Kerdy/Kerdy/Global/Literals/StringLiterals.swift
  Kerdy/Kerdy/Global/Protocol/SettingWrittenProtocol.swift
  Kerdy/Kerdy/Global/Utils/Util.swift
  Kerdy/Kerdy/InitialSetting/VC/SecondInitialSettingVC.swift
  Kerdy/Kerdy/InitialSetting/VC/ThirdInitialSettingVC.swift
  Kerdy/Kerdy/Notification/VC/NotificationVC.swift
  Kerdy/Kerdy/NotificationTag/Cell/TagCell.swift
  Kerdy/Kerdy/NotificationTag/VC/TagVC.swift
  Kerdy/Kerdy/Setting/Cell/SettingBasicCell.swift
  Kerdy/Kerdy/Setting/Cell/SettingProfileCell.swift
  Kerdy/Kerdy/Setting/Cell/SettingWriteCell.swift
  Kerdy/Kerdy/Setting/Model/ArticleResponseDTO.swift
  Kerdy/Kerdy/Setting/Model/CommentsResponseDTO.swift
  Kerdy/Kerdy/Setting/VC/BaseVC.swift
  Kerdy/Kerdy/Setting/VC/SettingVC.swift
  Kerdy/Kerdy/Setting/VC/SettingWrittenVC.swift
  Kerdy/Kerdy/Setting/ViewModel/SettingDataSource.swift
  Kerdy/Kerdy/Setting/ViewModel/SettingWrittenDataSource.swift
  Kerdy/Kerdy/TabBar/TabBarItemType.swift
  Kerdy/Kerdy/ViewController.swift
Labels: feat, 🐰정은🐰, design

#43 [Design] 42 초기 설정 UI 수정
  Core/Sources/Core/Views/InitialSettingSelectBtn.swift
  Core/Sources/Core/Views/InitialSettingStackView.swift
  Kerdy/Kerdy.xcodeproj/project.pbxproj
  Kerdy/Kerdy/InitialSetting/VC/FirstInitialSettingVC.swift
  Kerdy/Kerdy/InitialSetting/VC/FourthInitialSettingVC.swift
  Kerdy/Kerdy/InitialSetting/VC/SecondInitialSettingVC.swift
  Kerdy/Kerdy/InitialSetting/VC/ThirdInitialSettingVC.swift
  Kerdy/Kerdy/InitialSetting/ViewModel/CategoryViewModel.swift
  Kerdy/Kerdy/InitialSetting/ViewModel/ClubViewModel.swift
  Kerdy/Kerdy/InitialSetting/ViewModel/EducationViewModel.swift
Labels: design
