Repository Kerdy-iOS/Kerdy-iOS, pull requests merged in 2023-12, with the labels that each got.

#52 [Feat] 26 설정뷰 UI 로직 구현
  Kerdy/Kerdy.xcodeproj/project.pbxproj
  Kerdy/Kerdy.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Kerdy/Kerdy/Auth/ViewController/AuthVC.swift
  Kerdy/Kerdy/Auth/ViewController/AuthViewModel.swift
  Kerdy/Kerdy/BlockList/BlockListVC.swift
  Kerdy/Kerdy/Common/Base/BaseVC.swift
  Kerdy/Kerdy/Common/Base/RxViewController+.swift
  Kerdy/Kerdy/Global/KeyChain/KeyChainValue.swift
  Kerdy/Kerdy/Global/Network/APIManagers/SettingManager.swift
  Kerdy/Kerdy/Global/Network/APIServices/SettingAPI.swift
  Kerdy/Kerdy/Global/Network/DataModel/MemberProfileResponseDTO.swift
  Kerdy/Kerdy/Global/Protocol/ViewModelType.swift
  Kerdy/Kerdy/Notification/VC/NotificationVC.swift
  Kerdy/Kerdy/Resource/Colors/Colors.xcassets/kerdy_background.colorset/Contents.json
  Kerdy/Kerdy/Setting/Cell/SettingBasicCell.swift
  Kerdy/Kerdy/Setting/Cell/SettingProfileCell.swift
  Kerdy/Kerdy/Setting/Model/ProfileResponseDTO.swift
  Kerdy/Kerdy/Setting/Model/SettingBasicModel.swift
  Kerdy/Kerdy/Setting/Model/SettingSectionModel.swift
  Kerdy/Kerdy/Setting/SettingWritten/Cell/SettingWriteCell.swift
  Kerdy/Kerdy/Setting/SettingWritten/Model/ArticleResponseDTO.swift
  Kerdy/Kerdy/Setting/SettingWritten/Model/CommentsResponseDTO.swift
  Kerdy/Kerdy/Setting/SettingWritten/VC/SettingWrittenVC.swift
  Kerdy/Kerdy/Setting/SettingWritten/ViewModel/SettingWrittenDataSource.swift
  Kerdy/Kerdy/Setting/VC/BaseVC.swift
  Kerdy/Kerdy/Setting/VC/SettingVC.swift
  Kerdy/Kerdy/Setting/ViewModel/SettingDataSource.swift
  Kerdy/Kerdy/Setting/ViewModel/SettingViewModel.swift
  Kerdy/Kerdy/TabBar/TabBarVC.swift
  Kerdy/Kerdy/TermsOfUse/TermsOfUseVC.swift
Labels: feat, 🐰정은🐰

#55 [Feat] 51 작성한 글, 작성한 댓글 로직 구현
  Kerdy/Kerdy.xcodeproj/project.pbxproj
  Kerdy/Kerdy/Global/Network/APIManagers/CommentManager.swift
  Kerdy/Kerdy/Global/Network/APIManagers/FeedManager.swift
  Kerdy/Kerdy/Global/Network/APIServices/CommentAPI.swift
  Kerdy/Kerdy/Global/Network/APIServices/FeedAPI.swift
  Kerdy/Kerdy/Global/Network/DataModel/CommentsResponseDTO.swift
  Kerdy/Kerdy/Global/Network/DataModel/FeedResponseDTO.swift
  Kerdy/Kerdy/Setting/Cell/SettingProfileCell.swift
  Kerdy/Kerdy/Setting/SettingWritten/Model/ArticleResponseDTO.swift
  Kerdy/Kerdy/Setting/SettingWritten/Model/CommentsResponseDTO.swift
  Kerdy/Kerdy/Setting/VC/SettingVC.swift
  Kerdy/Kerdy/SettingWritten/Cell/SettingWriteCell.swift
  Kerdy/Kerdy/SettingWritten/VC/SettingCommentsVC.swift
  Kerdy/Kerdy/SettingWritten/VC/SettingFeedVC.swift
  Kerdy/Kerdy/SettingWritten/ViewModel/SettingCommenetViewModel.swift
  Kerdy/Kerdy/SettingWritten/ViewModel/SettingFeedViewModel.swift
  Kerdy/Kerdy/SettingWritten/ViewModel/SettingWrittenDataSource.swift
Labels: feat, 🐰정은🐰

#47 [Design] 38 행사 상세보기 UI 구현
  Kerdy/Kerdy.xcodeproj/project.pbxproj
  Kerdy/Kerdy/Event/View/EventCollectionViewCell.swift
  Kerdy/Kerdy/Event/View/EventVC.swift
  Kerdy/Kerdy/EventDetail/Models/EventSummaryModel.swift
  Kerdy/Kerdy/EventDetail/Models/PostListModel.swift
  Kerdy/Kerdy/EventDetail/ViewModel/CellProtocol.swift
  Kerdy/Kerdy/EventDetail/Views/Cells/EventDetailPhotoCVCell.swift
  Kerdy/Kerdy/EventDetail/Views/Cells/EventDetailPhotoTVCell.swift
  Kerdy/Kerdy/EventDetail/Views/Cells/EventDetailPostCVCell.swift
  Kerdy/Kerdy/EventDetail/Views/Cells/EventDetailPostTVCell.swift
  Kerdy/Kerdy/EventDetail/Views/EventDetailBottomView.swift
  Kerdy/Kerdy/EventDetail/Views/EventDetailViewController.swift
  Kerdy/Kerdy/EventDetail/Views/EventSummaryInfoView.swift
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_bookmark_off.imageset/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_bookmark_off.imageset/ic_bookmark_off.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_bookmark_off.imageset/ic_bookmark_off@2x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_bookmark_off.imageset/ic_bookmark_off@3x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_bookmark_on.imageset/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_bookmark_on.imageset/ic_bookmark_on.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_bookmark_on.imageset/ic_bookmark_on@2x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_bookmark_on.imageset/ic_bookmark_on@3x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_comment.imageset/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_comment.imageset/ic_comment.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_comment.imageset/ic_comment@2x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_comment.imageset/ic_comment@3x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_like.imageset/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_like.imageset/icon_like.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_like.imageset/icon_like@2x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_like.imageset/icon_like@3x.png
  Kerdy/Kerdy/Resource/Colors/Colors.xcassets/kerdy_red.colorset/Contents.json
Labels: 🐻‍❄️동현🐻‍❄️, design

#59 [Feat] 56 차단 목록 로직 구현
  Core/Sources/Core/Extension/UIColor+.swift
  Core/Sources/Core/Extension/UIImage+.swift
  Kerdy/Kerdy.xcodeproj/project.pbxproj
  Kerdy/Kerdy/BlockList/BlockListCell.swift
  Kerdy/Kerdy/BlockList/BlockListModel.swift
  Kerdy/Kerdy/BlockList/BlockListVC.swift
  Kerdy/Kerdy/BlockList/Cell/BlockListCell.swift
  Kerdy/Kerdy/BlockList/Model/BlockSectionModel.swift
  Kerdy/Kerdy/BlockList/VC/BlockListVC.swift
  Kerdy/Kerdy/BlockList/VC/PopUpView.swift
  Kerdy/Kerdy/BlockList/ViewModel/BlockListViewModel.swift
  Kerdy/Kerdy/Common/Base/Rx+UIButton.swift
  Kerdy/Kerdy/Global/Literals/StringLiterals.swift
  Kerdy/Kerdy/Global/Network/APIManagers/BlockManager.swift
  Kerdy/Kerdy/Global/Network/APIServices/BlockAPI.swift
  Kerdy/Kerdy/Global/Network/DataModel/BlockReponseDTO.swift
  Kerdy/Kerdy/Global/Network/DataModel/MemberProfileResponseDTO.swift
  Kerdy/Kerdy/Global/Network/Foundation/EmptyResponse.swift
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_emptyLogo.imageset/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_emptyLogo.imageset/ic_emptyLogo.pdf
  Kerdy/Kerdy/Resource/Colors/Colors.xcassets/kerdy_red.colorset/Contents.json
  Kerdy/Kerdy/Setting/VC/SettingVC.swift
Labels: feat, 🐰정은🐰

#64 [Feat] 57 로그아웃, 계정 삭제 로직 구현
  Core/Sources/Core/Extension/UILabel+.swift
  Kerdy/Kerdy.xcodeproj/project.pbxproj
  Kerdy/Kerdy/BlockList/VC/BlockListVC.swift
  Kerdy/Kerdy/Common/PopUpView.swift
  Kerdy/Kerdy/Global/Enum/AuthType.swift
  Kerdy/Kerdy/Global/KeyChain/KeyChainManager.swift
  Kerdy/Kerdy/Global/Network/APIManagers/SettingManager.swift
  Kerdy/Kerdy/Global/Network/APIServices/SettingAPI.swift
  Kerdy/Kerdy/Setting/VC/SettingVC.swift
  Kerdy/Kerdy/Setting/ViewModel/SettingViewModel.swift
Labels: feat, 🐰정은🐰

#65 [Feat] 58 답글 UI 및 로직 구현
  Core/Sources/Core/Extension/UIImage+.swift
  Core/Sources/Core/Extension/UITextFeild+.swift
  Kerdy/Kerdy.xcodeproj/project.pbxproj
  Kerdy/Kerdy.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Kerdy/Kerdy/Auth/ViewController/AuthViewModel.swift
  Kerdy/Kerdy/BlockList/ViewModel/BlockListViewModel.swift
  Kerdy/Kerdy/Comments/Cell/ChildCommentsCell.swift
  Kerdy/Kerdy/Comments/Model/CommentsSection.swift
  Kerdy/Kerdy/Comments/VC/CommentsVC.swift
  Kerdy/Kerdy/Comments/View/CommentsContainerView.swift
  Kerdy/Kerdy/Comments/View/CommentsHeaderView.swift
  Kerdy/Kerdy/Comments/ViewModel/CommentsViewModel.swift
  Kerdy/Kerdy/Global/Literals/StringLiterals.swift
  Kerdy/Kerdy/Global/Network/APIManagers/CommentManager.swift
  Kerdy/Kerdy/Global/Network/APIServices/CommentAPI.swift
  Kerdy/Kerdy/Global/Network/DataModel/CommentsResponseDTO.swift
  Kerdy/Kerdy/Global/Network/DataModel/FeedResponseDTO.swift
  Kerdy/Kerdy/Global/Network/Foundation/NetworkError.swift
  Kerdy/Kerdy/Global/Protocol/SettingWrittenProtocol.swift
  Kerdy/Kerdy/Kerdy.entitlements
  Kerdy/Kerdy/Notification/ViewModel/NotificationViewModel.swift
  Kerdy/Kerdy/NotificationTag/ViewModel/TagViewModel.swift
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/button/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/button/btn_dot.imageset/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/button/btn_dot.imageset/btn_dot.pdf
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_commentsArrow.imageset/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_commentsArrow.imageset/ic_commentsArrow.pdf
  Kerdy/Kerdy/Setting/ViewModel/SettingViewModel.swift
  Kerdy/Kerdy/SettingWritten/Cell/SettingWriteCell.swift
  Kerdy/Kerdy/SettingWritten/VC/SettingCommentsVC.swift
  Kerdy/Kerdy/SettingWritten/ViewModel/SettingCommenetViewModel.swift
  Kerdy/Kerdy/SettingWritten/ViewModel/SettingFeedViewModel.swift
  Kerdy/Kerdy/SettingWritten/ViewModel/SettingWrittenDataSource.swift
Labels: feat, 🐰정은🐰

#61 [Feat] 행사 목록 API 연결
  Kerdy/Kerdy/Event/Model/Event.swift
  Kerdy/Kerdy/Event/Model/EventFilter.swift
  Kerdy/Kerdy/Event/View/EventCollectionViewCell.swift
  Kerdy/Kerdy/Event/View/EventTableViewCell.swift
  Kerdy/Kerdy/Event/View/EventVC.swift
  Kerdy/Kerdy/Event/ViewModel/EventViewModel.swift
  Kerdy/Kerdy/EventDetail/Views/Cells/EventDetailPostCVCell.swift
  Kerdy/Kerdy/Global/Network/APIManagers/EventManager.swift
  Kerdy/Kerdy/Global/Network/APIServices/EventAPI.swift
Labels: feat, 🐻‍❄️동현🐻‍❄️

#73 [Design] 54 내 명함 UI 구현
  Core/Sources/Core/Views/InitialSettingSelectBtn.swift
  Core/Sources/Core/Views/InitialSettingStackView.swift
  Kerdy/Kerdy.xcodeproj/project.pbxproj
  Kerdy/Kerdy/InitialSetting/Cell/InitialSettingCell.swift
  Kerdy/Kerdy/InitialSetting/Model/MemberInfo.swift
  Kerdy/Kerdy/InitialSetting/Network/ActivityAPI.swift
  Kerdy/Kerdy/InitialSetting/Network/ActivityModel.swift
  Kerdy/Kerdy/InitialSetting/Network/RegisterMemberAPI.swift
  Kerdy/Kerdy/InitialSetting/VC/FirstInitialSettingVC.swift
  Kerdy/Kerdy/InitialSetting/VC/FourthInitialSettingVC.swift
  Kerdy/Kerdy/InitialSetting/VC/SecondInitialSettingVC.swift
  Kerdy/Kerdy/InitialSetting/VC/ThirdInitialSettingVC.swift
  Kerdy/Kerdy/InitialSetting/ViewModel/CategoryViewModel.swift
  Kerdy/Kerdy/InitialSetting/ViewModel/ClubViewModel.swift
  Kerdy/Kerdy/InitialSetting/ViewModel/EducationViewModel.swift
  Kerdy/Kerdy/MyProfile/Cell/ProfileActivityCell.swift
  Kerdy/Kerdy/MyProfile/MyBusinessCardVC.swift
  Kerdy/Kerdy/MyProfile/UserImageVC.swift
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_activity.imageset/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_activity.imageset/activity1x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_activity.imageset/activity2x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_activity.imageset/activity3x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_dot.imageset/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_dot.imageset/dot1x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_dot.imageset/dot2x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_dot.imageset/dot3x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_edit_profile.imageset/1x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_edit_profile.imageset/2x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_edit_profile.imageset/3x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_edit_profile.imageset/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/image/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/image/img_user.imageset/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/image/img_user.imageset/스크린샷 2023-12-14 오전 1.03.36.png
  Kerdy/Kerdy/TabBar/TabBarVC.swift
Labels: 🐶다경🐶, design

#72 [Design] 48 tags 선택 ui 수정
  Kerdy/Kerdy.xcodeproj/project.pbxproj
  Kerdy/Kerdy/Common/DateTransferDelegate.swift
  Kerdy/Kerdy/Event/Model/FilterType.swift
  Kerdy/Kerdy/Event/ViewModel/EventViewModel.swift
  Kerdy/Kerdy/Filter/DateFilter/Views/DateFilterViewController.swift
  Kerdy/Kerdy/Filter/DateFilter/Views/PeriodView.swift
  Kerdy/Kerdy/Filter/Filter/Models/EventFilter.swift
  Kerdy/Kerdy/Filter/Filter/Models/FilterStatus.swift
  Kerdy/Kerdy/Filter/Filter/ViewModel/FilterViewModel.swift
  Kerdy/Kerdy/Filter/Filter/Views/DateFilterView.swift
  Kerdy/Kerdy/Filter/Filter/Views/DateSelectBtn.swift
  Kerdy/Kerdy/Filter/Filter/Views/FilterBtn.swift
  Kerdy/Kerdy/Filter/Filter/Views/FilterVC.swift
  Kerdy/Kerdy/Filter/Filter/Views/ProgressFilterView.swift
  Kerdy/Kerdy/Filter/Filter/Views/SupplementaryViews/FilterFooterView.swift
  Kerdy/Kerdy/Filter/Filter/Views/SupplementaryViews/FilterHeaderView.swift
  Kerdy/Kerdy/Filter/Filter/Views/TagFilterCollectionViewCell.swift
  Kerdy/Kerdy/Filter/Filter/Views/TagFilterView.swift
  Kerdy/Kerdy/Global/Network/APIManagers/EventManager.swift
  Kerdy/Kerdy/Global/Network/APIServices/EventAPI.swift
Labels: fix, 🐻‍❄️동현🐻‍❄️, design
