Repository Kerdy-iOS/Kerdy-iOS, pull requests merged in 2024-01, with the labels that each got.

#74 [Design] 54 프로필 수정 UI 구현
  Kerdy/Kerdy.xcodeproj/project.pbxproj
  Kerdy/Kerdy/MyProfile/Cell/ProfileActivityCell.swift
  Kerdy/Kerdy/MyProfile/Cell/ProfileTagCell.swift
  Kerdy/Kerdy/MyProfile/ProfileTagBtn.swift
  Kerdy/Kerdy/MyProfile/VC/ActivityEditHalfVC.swift
  Kerdy/Kerdy/MyProfile/VC/MyBusinessCardVC.swift
  Kerdy/Kerdy/MyProfile/VC/ProfileEditHalfVC.swift
  Kerdy/Kerdy/MyProfile/VC/ProfileEditVC.swift
  Kerdy/Kerdy/MyProfile/VC/UserImageVC.swift
  Kerdy/Kerdy/MyProfile/ViewModel/ProfileViewModel.swift
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_addButton_filled.imageset/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_addButton_filled.imageset/추가버튼1.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_addButton_filled.imageset/추가버튼2.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_addButton_filled.imageset/추가버튼3.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_camera.imageset/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_camera.imageset/camera1.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_camera.imageset/camera2.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_camera.imageset/camera3.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_grabbar.imageset/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_grabbar.imageset/Rectangle1.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_grabbar.imageset/Rectangle2.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_grabbar.imageset/Rectangle3.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_pencil.imageset/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_pencil.imageset/pencil1.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_pencil.imageset/pencil2.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_pencil.imageset/pencil3.png
Labels: 🐶다경🐶, design

#76 [Feat] 62 필터 적용 로직 추가
  Core/Sources/Core/Extension/UIView+.swift
  Kerdy/Kerdy.xcodeproj/project.pbxproj
  Kerdy/Kerdy/Event/Model/Event.swift
  Kerdy/Kerdy/Event/View/EventTableViewCell.swift
  Kerdy/Kerdy/Event/View/EventVC.swift
  Kerdy/Kerdy/Event/View/FilterCollectionViewCell.swift
  Kerdy/Kerdy/Event/View/ItemCountView.swift
  Kerdy/Kerdy/Event/View/TagView.swift
  Kerdy/Kerdy/Event/ViewModel/EventViewModel.swift
  Kerdy/Kerdy/Filter/Filter/ViewModel/FilterViewModel.swift
  Kerdy/Kerdy/Filter/Filter/Views/FilterVC.swift
  Kerdy/Kerdy/Filter/Filter/Views/TagFilterCollectionViewCell.swift
  Kerdy/Kerdy/Global/Network/APIManagers/EventManager.swift
  Kerdy/Kerdy/Global/Network/APIManagers/ImageManager.swift
  Kerdy/Kerdy/Global/Network/APIManagers/ScrapManager.swift
  Kerdy/Kerdy/Global/Network/APIServices/EventAPI.swift
  Kerdy/Kerdy/Global/Network/APIServices/ImageAPI.swift
  Kerdy/Kerdy/Global/Network/APIServices/ScrapAPI.swift
  Kerdy/Kerdy/Global/Network/Foundation/BaseInfoManager.swift
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/image/img_user.imageset/Contents.json
Labels: feat, fix, 🐻‍❄️동현🐻‍❄️, design

#71 [Fix] 67 알림 설정 UI 및 FCM 구현
  Kerdy/Kerdy.xcodeproj/project.pbxproj
  Kerdy/Kerdy.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Kerdy/Kerdy/Application/AppDelegate.swift
  Kerdy/Kerdy/Auth/ViewController/AuthViewModel.swift
  Kerdy/Kerdy/Event/Model/EventFilter.swift
  Kerdy/Kerdy/EventDetail/Views/Cells/EventDetailPostCVCell.swift
  Kerdy/Kerdy/EventDetail/Views/Cells/EventDetailPostTVCell.swift
  Kerdy/Kerdy/EventDetail/Views/EventDetailBottomView.swift
  Kerdy/Kerdy/Global/KeyChain/KeyChainManager.swift
  Kerdy/Kerdy/Global/KeyChain/KeyChainValue.swift
  Kerdy/Kerdy/Global/KeyChain/UserDefaultsManager.swift
  Kerdy/Kerdy/Global/Literals/StringLiterals.swift
  Kerdy/Kerdy/Global/Network/APIManagers/LoginManager.swift
  Kerdy/Kerdy/Global/Network/APIServices/EventAPI.swift
  Kerdy/Kerdy/Global/Network/APIServices/LoginAPI.swift
  Kerdy/Kerdy/Global/Network/APIServices/ScrapAPI.swift
  Kerdy/Kerdy/Global/Network/DataModel/TagsResponseDTO.swift
  Kerdy/Kerdy/Global/Network/Foundation/KerdyAPI.swift
  Kerdy/Kerdy/Kerdy.entitlements
  Kerdy/Kerdy/Notification/Cell/HeaderNotificationCell.swift
  Kerdy/Kerdy/Notification/Cell/NotificationCell.swift
  Kerdy/Kerdy/Notification/VC/NotificationVC.swift
  Kerdy/Kerdy/Notification/ViewModel/NotificationSectionItem.swift
  Kerdy/Kerdy/Notification/ViewModel/NotificationViewModel.swift
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_addButton_filled.imageset/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_addButton_filled.imageset/ic_addButton_filled.pdf
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_addButton_filled.imageset/추가버튼1.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_addButton_filled.imageset/추가버튼2.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_addButton_filled.imageset/추가버튼3.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/image/img_user.imageset/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/image/img_user.imageset/ic_user.png
  Kerdy/Kerdy/Resource/GoogleService-Info.plist
  Kerdy/Kerdy/Resource/Info.plist
  Kerdy/Kerdy/Setting/VC/SettingVC.swift
  Kerdy/Kerdy/SettingWritten/VC/SettingCommentsVC.swift
  Kerdy/Kerdy/TagNotification/Cell/TagCell.swift
  Kerdy/Kerdy/TagNotification/TagCollectionViewFlowLayout.swift
  Kerdy/Kerdy/TagNotification/VC/TagVC.swift
  Kerdy/Kerdy/TagNotification/ViewModel/TagModel.swift
  Kerdy/Kerdy/TagNotification/ViewModel/TagViewModel.swift
  Kerdy/Kerdy/View/SwitchNotificationView.swift
Labels: feat, fix, 🐰정은🐰, design

#81 [Feat] 80 알림 보관함 UI 구현
  Core/Sources/Core/Extension/UIImage+.swift
  Kerdy/Kerdy.xcodeproj/project.pbxproj
  Kerdy/Kerdy/Event/View/EventVC.swift
  Kerdy/Kerdy/Global/Literals/StringLiterals.swift
  Kerdy/Kerdy/Global/Network/APIManagers/NotificationManager.swift
  Kerdy/Kerdy/Global/Network/APIServices/EventAPI.swift
  Kerdy/Kerdy/Global/Network/APIServices/NotificationAPI.swift
  Kerdy/Kerdy/Global/Network/DataModel/ArchiveResponseDTO.swift
  Kerdy/Kerdy/Global/Network/DataModel/CommentsResponseDTO.swift
  Kerdy/Kerdy/Global/Network/DataModel/FeedResponseDTO.swift
  Kerdy/Kerdy/Global/Network/Foundation/KerdyAPI.swift
  Kerdy/Kerdy/Global/Utils/Util.swift
  Kerdy/Kerdy/InitialSetting/Model/MemberInfo.swift
  Kerdy/Kerdy/NotificationArchive/Cell/ArchiveCell.swift
  Kerdy/Kerdy/NotificationArchive/Model/ArchiveSectionItem.swift
  Kerdy/Kerdy/NotificationArchive/VC/NotificationArchiveVC.swift
  Kerdy/Kerdy/NotificationArchive/View/ArchiveHeaderView.swift
  Kerdy/Kerdy/NotificationArchive/ViewModel/ArchiveViewModel.swift
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_archiveCancel.imageset/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_archiveCancel.imageset/ic_archiveCancel.pdf
  Kerdy/Kerdy/TabBar/TabBarVC.swift
Labels: feat, 🐰정은🐰

#82 [Feat] 66 댓글 Alert 구현
  Kerdy/Kerdy.xcodeproj/project.pbxproj
  Kerdy/Kerdy/Application/SceneDelegate.swift
  Kerdy/Kerdy/Auth/ViewController/AuthVC.swift
  Kerdy/Kerdy/Auth/ViewController/AuthViewModel.swift
  Kerdy/Kerdy/BlockList/VC/BlockListVC.swift
  Kerdy/Kerdy/BlockList/ViewModel/BlockListViewModel.swift
  Kerdy/Kerdy/CommentModal/Model/CommonModalItem.swift
  Kerdy/Kerdy/CommentModal/VC/ModalVC.swift
  Kerdy/Kerdy/CommentModal/View/CommonModalCell.swift
  Kerdy/Kerdy/CommentModal/View/ReportCompletedView.swift
  Kerdy/Kerdy/CommentModal/ViewModel/CommonModalViewModel.swift
  Kerdy/Kerdy/Comments/Cell/ChildCommentsCell.swift
  Kerdy/Kerdy/Comments/VC/CommentsVC.swift
  Kerdy/Kerdy/Comments/View/CommentsContainerView.swift
  Kerdy/Kerdy/Comments/View/CommentsHeaderView.swift
  Kerdy/Kerdy/Comments/ViewModel/CommentsViewModel.swift
  Kerdy/Kerdy/Common/ModalTopView.swift
  Kerdy/Kerdy/Global/Enum/AlertType.swift
  Kerdy/Kerdy/Global/Network/APIManagers/CommentManager.swift
  Kerdy/Kerdy/Global/Network/APIManagers/ReportManager.swift
  Kerdy/Kerdy/Global/Network/APIServices/CommentAPI.swift
  Kerdy/Kerdy/Global/Network/APIServices/ImageAPI.swift
  Kerdy/Kerdy/Global/Network/APIServices/ReportAPI.swift
  Kerdy/Kerdy/Global/Network/DataModel/BlockReponseDTO.swift
  Kerdy/Kerdy/Global/Network/DataModel/CommentsResponseDTO.swift
  Kerdy/Kerdy/Global/Protocol/DateTransferDelegate.swift
  Kerdy/Kerdy/Notification/ViewModel/NotificationViewModel.swift
  Kerdy/Kerdy/Setting/VC/SettingVC.swift
  Kerdy/Kerdy/Setting/ViewModel/SettingViewModel.swift
  Kerdy/Kerdy/SettingWritten/VC/SettingCommentsVC.swift
  Kerdy/Kerdy/SettingWritten/VC/SettingFeedVC.swift
  Kerdy/Kerdy/SettingWritten/ViewModel/SettingCommenetViewModel.swift
  Kerdy/Kerdy/TabBar/TabBarVC.swift
  Kerdy/Kerdy/TagNotification/VC/TagVC.swift
Labels: feat, 🐰정은🐰

#79 [Feat] 68 검색 기능 추가
  Kerdy/Kerdy.xcodeproj/project.pbxproj
  Kerdy/Kerdy/Event/View/EventVC.swift
  Kerdy/Kerdy/Event/View/ItemCountView.swift
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/Search/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_clear.imageset/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_clear.imageset/ic_clear@1x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_clear.imageset/ic_clear@2x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_clear.imageset/ic_clear@3x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/no_result.imageset/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/no_result.imageset/no_result@1x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/no_result.imageset/no_result@2x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/no_result.imageset/no_result@3x.png
  Kerdy/Kerdy/SearchEvent/Model/SearchStatus.swift
  Kerdy/Kerdy/SearchEvent/ViewModel/SearchEventViewModel.swift
  Kerdy/Kerdy/SearchEvent/Views/RecentDescriptionView.swift
  Kerdy/Kerdy/SearchEvent/Views/RecentKeyWordTableViewCell.swift
  Kerdy/Kerdy/SearchEvent/Views/SearchViewController.swift
Labels: enhancement, feat, 🐻‍❄️동현🐻‍❄️, design
