Repository Kerdy-iOS/Kerdy-iOS, pull requests merged in 2024-02, with the labels that each got.

#90 [Fix] 78 이벤트 목록 tag 깨짐 현상 수정 및 UI 리팩토링
  Kerdy/Kerdy.xcodeproj/project.pbxproj
  Kerdy/Kerdy/Event/Model/Event.swift
  Kerdy/Kerdy/Event/View/CategoryView.swift
  Kerdy/Kerdy/Event/View/EventCollectionViewCell.swift
  Kerdy/Kerdy/Event/View/EventTableViewCell.swift
  Kerdy/Kerdy/Event/View/EventVC.swift
  Kerdy/Kerdy/Event/View/FilterCollectionViewCell.swift
  Kerdy/Kerdy/Event/View/FilterSettingBtn.swift
  Kerdy/Kerdy/Event/View/ItemCountView.swift
  Kerdy/Kerdy/Event/View/TagView.swift
  Kerdy/Kerdy/Event/ViewModel/EventViewModel.swift
  Kerdy/Kerdy/EventDetail/Views/Cells/EventDetailPhotoCVCell.swift
  Kerdy/Kerdy/EventDetail/Views/Cells/EventDetailPostCVCell.swift
  Kerdy/Kerdy/Filter/Filter/Models/Tag.swift
  Kerdy/Kerdy/Global/Network/APIManagers/EventManager.swift
  Kerdy/Kerdy/Global/Network/APIManagers/ScrapManager.swift
  Kerdy/Kerdy/Global/Network/APIServices/EventAPI.swift
  Kerdy/Kerdy/Global/Network/APIServices/ScrapAPI.swift
  Kerdy/Kerdy/Global/Network/DataModel/EventResponseDTO.swift
  Kerdy/Kerdy/Global/Network/DataModel/RecruitmentResponseDTO.swift
  Kerdy/Kerdy/Global/Utils/DateManager.swift
  Kerdy/Kerdy/Global/Utils/Util.swift
  Kerdy/Kerdy/SearchEvent/ViewModel/SearchEventViewModel.swift
Labels: fix, 🐻‍❄️동현🐻‍❄️

#91 [Fix] 89 알림 로직 변경
  Core/Sources/Core/Extension/UIApplication+.swift
  Kerdy/Kerdy.xcodeproj/project.pbxproj
  Kerdy/Kerdy.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Kerdy/Kerdy/Application/AppDelegate.swift
  Kerdy/Kerdy/Auth/ViewController/AuthViewModel.swift
  Kerdy/Kerdy/CommentModal/VC/ModalVC.swift
  Kerdy/Kerdy/Comments/VC/CommentsVC.swift
  Kerdy/Kerdy/Event/View/EventVC.swift
  Kerdy/Kerdy/Global/KeyChain/UserDefaultsManager.swift
  Kerdy/Kerdy/Notification/Cell/HeaderNotificationCell.swift
  Kerdy/Kerdy/Notification/VC/NotificationVC.swift
  Kerdy/Kerdy/Notification/ViewModel/NotificationSectionItem.swift
  Kerdy/Kerdy/Notification/ViewModel/NotificationViewModel.swift
  Kerdy/Kerdy/NotificationArchive/ViewModel/ArchiveViewModel.swift
Labels: fix, 🐰정은🐰

#86 [Feat] 44 초기설정 로직 구현
  Kerdy/Kerdy.xcodeproj/project.pbxproj
  Kerdy/Kerdy/Auth/ViewController/AuthVC.swift
  Kerdy/Kerdy/Global/Network/APIManagers/MyProfileManager.swift
  Kerdy/Kerdy/Global/Network/APIServices/MyProfileAPI.swift
  Kerdy/Kerdy/InitialSetting/Model/MemberInfo.swift
  Kerdy/Kerdy/InitialSetting/Network/ActivityAPI.swift
  Kerdy/Kerdy/InitialSetting/Network/ActivityModel.swift
  Kerdy/Kerdy/InitialSetting/Network/RegisterMemberAPI.swift
  Kerdy/Kerdy/InitialSetting/VC/FirstInitialSettingVC.swift
  Kerdy/Kerdy/InitialSetting/VC/FourthInitialSettingVC.swift
  Kerdy/Kerdy/InitialSetting/VC/SecondInitialSettingVC.swift
  Kerdy/Kerdy/InitialSetting/VC/ThirdInitialSettingVC.swift
  Kerdy/Kerdy/InitialSetting/ViewModel/CategoryViewModel.swift
  Kerdy/Kerdy/InitialSetting/ViewModel/ClubViewModel.swift
  Kerdy/Kerdy/InitialSetting/ViewModel/EducationViewModel.swift
  Kerdy/Kerdy/InitialSetting/ViewModel/InitialSettingViewModel.swift
  Kerdy/Kerdy/Resource/Base-Info.plist
Labels: feat, 🐶다경🐶

#92 [Feat] 63 행사 상세보기 API 연결
  Kerdy/Kerdy.xcodeproj/project.pbxproj
  Kerdy/Kerdy/Event/View/EventVC.swift
  Kerdy/Kerdy/EventDetail/ViewModel/EventDetailViewModel.swift
  Kerdy/Kerdy/EventDetail/Views/Cells/EventDetailCVCell.swift
  Kerdy/Kerdy/EventDetail/Views/Cells/EventDetailFeedTVCell.swift
  Kerdy/Kerdy/EventDetail/Views/Cells/EventDetailPhotoCVCell.swift
  Kerdy/Kerdy/EventDetail/Views/Cells/EventDetailPhotoTVCell.swift
  Kerdy/Kerdy/EventDetail/Views/Cells/EventDetailPostCVCell.swift
  Kerdy/Kerdy/EventDetail/Views/Cells/EventDetailRecruitTVCell.swift
  Kerdy/Kerdy/EventDetail/Views/Cells/EventDetailTagCell.swift
  Kerdy/Kerdy/EventDetail/Views/EventDetailBottomView.swift
  Kerdy/Kerdy/EventDetail/Views/EventDetailViewController.swift
  Kerdy/Kerdy/EventDetail/Views/EventSummaryInfoView.swift
Labels: feat, fix, 🐻‍❄️동현🐻‍❄️

#85 [Design] 83 채팅 목록, 채팅 화면 UI 구현
  Kerdy/Kerdy.xcodeproj/project.pbxproj
  Kerdy/Kerdy/Chat/ChatVC.swift
  Kerdy/Kerdy/Chat/ViewModel/ChatViewModel.swift
  Kerdy/Kerdy/Chat/Views/ChatListCollectionViewCell.swift
  Kerdy/Kerdy/Chat/Views/ChatVC.swift
  Kerdy/Kerdy/ChatDetail/ViewModel/ChatDetailCellViewModel.swift
  Kerdy/Kerdy/ChatDetail/ViewModel/ChatDetailViewModel.swift
  Kerdy/Kerdy/ChatDetail/Views/ChatDateSupplementaryView.swift
  Kerdy/Kerdy/ChatDetail/Views/ChatDetailViewController.swift
  Kerdy/Kerdy/ChatDetail/Views/IncomingChatCollectionViewCell.swift
  Kerdy/Kerdy/ChatDetail/Views/MyChatCollectionViewCell.swift
  Kerdy/Kerdy/Global/Network/DataModel/MessageRoomResponseDTO.swift
  Kerdy/Kerdy/Global/Utils/Util.swift
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_more.imageset/Contents.json
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_more.imageset/ic_more@1x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_more.imageset/ic_more@2x.png
  Kerdy/Kerdy/Resource/Assets/Assets.xcassets/icon/ic_more.imageset/ic_more@3x.png
Labels: 🐻‍❄️동현🐻‍❄️, design
